version: '3'
services:
  mongodb:
    image: sanrocks12/arep-taller5-terminado:bdproject
    container_name: projectdb
    ports:
      - "27017:27017"
    networks:
      - redConectada
    command: 'mongod'

  logroundrobin:
    image: sanrocks12/arep-taller5-terminado:logroundrobin
    ports:
      - "4567:4567"
    container_name: logroundrobin
    networks:
      - redConectada

  logservice1:
    image: sanrocks12/arep-taller5-terminado:logservice
    ports:
      - "4568:4568"
    container_name: logservice1
    networks:
      - redConectada

  logservice2:
    image: sanrocks12/arep-taller5-terminado:logservice
    ports:
      - "4569:4568"
    container_name: logservice2
    networks:
      - redConectada

  logservice3:
    image: sanrocks12/arep-taller5-terminado:logservice
    ports:
      - "4570:4568"
    container_name: logservice3
    networks:
      - redConectada

networks:
  redConectada:
